#!/usr/bin/bash

if [ "$1" == "-h" ] || [ $# -eq 0 ]; then
  echo "Usage: `basename $0` <yyyymmdd>"
  exit 0
fi

dayt=${1}
year=`date -d $dayt +%Y`
jday=`date -d $dayt +%j`
dateJ="$year.$jday"

find /mnt/mvohvs3/MVOSeisD6/mseed/MV -name "${dateJ}*" -exec cp "{}" ./  \;
