#!/usr/bin/perl
#
# Finds WAV file for date and time and duration
#
# R.C.Stewart, 2025-01-14

use strict;
use warnings;

my $numArgs = $#ARGV + 1;

if( $numArgs < 2 ){ 
    print "Not enough arguments", "\n";
    print "usage: findWav yyyy-mm-dd hh:mm:ss", "\n";
} else {

    my $eventDate = $ARGV[0];
    my $eventTime = $ARGV[1];
    my $windowLength;
    if( $numArgs == 3 ){
        $windowLength = $ARGV[2];
    } else {
        $windowLength = 0;
    }

    my($yyyy,$mm,$dd) = split( '-', $eventDate );
    my($hh,$mi,$sss) = split( ':', $eventTime );

    my $dirWavRoot;
    if( $yyyy < 2011 ){
        $dirWavRoot = '/mnt/mvohvs3/MVOSeisD6/WAV/DSNC_';
    } else {
        $dirWavRoot = '/mnt/mvofls2/Seismic_Data/WAV/DSNC_';
    }
    my $dirWav = join( '/', $dirWavRoot, $yyyy, $mm );

    my $miFloor;
    if( $mi < 20 ) {
        $miFloor = "00";
    } elsif( $mi < 40 ) {
        $miFloor = "20";
    } else {
        $miFloor = "40";
    }

    my $joiner = "-";
    my $fileWavRoot = join( $joiner, $yyyy, $mm, $dd, $hh );
    my $fileWav = join( '', $fileWavRoot, $miFloor, '*' );
    $fileWav = join( '/', $dirWav, $fileWav );
    my $cmd = "ls -1 $fileWav 2>/dev/null";
    system( $cmd );

    $joiner = "_";
    $fileWavRoot = join( $joiner, $yyyy, $mm, $dd, $hh );
    $fileWav = join( '', $fileWavRoot, $miFloor, '*' );
    $fileWav = join( '/', $dirWav, $fileWav );
    $cmd = "ls -1 $fileWav 2>/dev/null";
    system( $cmd );

    my $dirRbuffer= '/mnt/mvofls2/Seismic_Data/rbuffers';
    $fileWav = join( '', $fileWavRoot, $miFloor, '*' );
    $fileWav = join( '/', $dirRbuffer, $fileWav );
    $cmd = "ls -1 $fileWav 2>/dev/null";
    system( $cmd );


}
