#!/usr/bin/bash

if [ -z "$1" ]
then
	echo "Argument needed, twit!"
else
	idString=$1

    if [[ "$idString" == *.tmp ]]; then
        fileIn=${idString}
    else
        fileIn="${idString}.tmp"
    fi
    echo $fileIn

    fileOut="${fileIn/tmp/txt}"
    echo $fileOut

    mulplt2vtse.pl $fileIn > $fileOut
    echo -n "Number of events: "
    mulplt2vtse.pl $fileIn $fileOut | wc -l


    echo -n "First event: "
    mulplt2vtse2.pl $fileIn | head -1
    echo -n "Last event:  "
    mulplt2vtse2.pl $fileIn | tail -1

fi
