#!/bin/bash
#
# Does full or incremental tar backup
# If it has any argument, it will do an incremental backup
#
# R.C. Stewart 2025-05-01

dirBackup='/mnt/mvohvs3/MVOSeisD6/backups/cron'

if [[ $HOSTNAME == 'winston1' ]]; then
    if [ $USER == "mvo" ]; then
        excludes='--exclude=/home/mvo/data'
    else
        excludes=''
    fi
elif [[ $HOSTNAME == 'opsrm04' || $HOSTNAME == 'opsrm05' || $HOSTNAME == 'opsrm06' ]]; then
    excludes=''
elif [[ $HOSTNAME == 'opsproc3' ]]; then
    excludes='--exclude=/home/seisan/data --exclude="home/seisan/Dropbox --exclude=/home/seisan/tmp* --exclude=/home/seisan/veryTmp*'
else
    excludes=''
fi


if [ -n "$1" ]; then
    tarFile="${HOSTNAME}"-"${USER}"-`date +"%Y%m%d"`-level1.tar.gz
else
    tarFile="${HOSTNAME}"-"${USER}"-`date +"%Y%m%d"`-level0.tar.gz
fi

snarFile="${HOSTNAME}"-"${USER}".snar

tar -czf $dirBackup/$tarFile "${excludes}" -g $dirBackup/$snarFile /home/"${USER}" >> /dev/null 2&>1
