#!/bin/bash
#
# Does full or incremental tar backup
# If it has any argument, it will do an incremental backup
# Should be run as root
#
# R.C. Stewart 2025-05-01

host=`hostname`
user=`whoami`
dirBackup='/mnt/mvohvs3/MVOSeisD6/backups/cron'

if [ "$host" == "winston1" ]; then
    if [ "$user" == "mvo" ]; then
        excludes='--exclude="/home/mvo/data"'
    else
        excludes=''
    fi
elif ["$host" == "opsrm04"] || ["$host" == "opsrm05"] || ["$host" == "opsrm06"]; then
    excludes=''
elif ["$host" == "opsproc3"]; then
    excludes=''
fi


if [ -n "$1" ]; then
    tarFile=$host-$user-`date +"%Y%m%d"`-level1.tar.gz
else
    tarFile=$host-$user-`date +"%Y%m%d"`-level0.tar.gz
fi

tar -czf $dirBackup/$tarFile $excludes -g $dirBackup/$host-$user.snar /home/$user >> /dev/null 2&>1
